# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bundle.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62undle.proto\"8\n\x08\x45xercise\x12\r\n\x05title\x18\x01 \x02(\t\x12\x0f\n\x07tooltip\x18\x02 \x01(\t\x12\x0c\n\x04\x66ile\x18\x03 \x02(\t\"&\n\x06\x42undle\x12\x1c\n\texercises\x18\x01 \x03(\x0b\x32\t.Exercise')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bundle_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXERCISE._serialized_start=16
  _EXERCISE._serialized_end=72
  _BUNDLE._serialized_start=74
  _BUNDLE._serialized_end=112
# @@protoc_insertion_point(module_scope)

